### ISSUE TITLE
关于修复repo

### ISSUE THREAD

**Issue by broncotc** [MrTunnels/nitic#1]
个人认为此repo极为混乱，不建议长期维护。

以下是具体的意见：
- 原版nitic使用的license是MIT license，请考虑更换为GPL Licesnse发布是否合适
- 由于repo较为混乱，且前端升级困难，请考虑维护当前代码的成本与重构/重写的成本
- 如果需要教育授权的phpstorm/webstorm（或者其他jetbrains软件）可以联系我（自己直接申请jb的edu license当然更好），我手头有多余的授权。我相信这两个IDE能提升你们维护/重写repo的效率。

**Comment by hqy2000** [comment]
1.代码清理/整合会在当前版本的功能完全实现后进行
2.目前暂时没有重构计划（即暂时不对polymer版本进行升级）

**Comment by hqy2000** [comment]
嗯 彻底弃坑跑路了
